[package]
name = "fzfmenu"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
serde = { version = "1.0.219", features = ["derive"] }
shell-quote = "0.7.2"
toml = "0.9.5"
