[package]
name = "fzfmenu"
version = "0.4.4"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
