[[plugins]]
name = "app_launcher"
description = "Launch applications based on your desktop environment."
prefix = ""
picker = "python ~/.config/fzfmenu/plugins/app_launcher.py picker"
runner = "python ~/.config/fzfmenu/plugins/app_launcher.py runner"

[[plugins]]
name = "killer"
description = "Find and terminate running processes."
prefix = "kl "
picker = "python ~/.config/fzfmenu/plugins/killer.py picker"
runner = "python ~/.config/fzfmenu/plugins/killer.py runner"
reload = true

[[plugins]]
name = "jumper"
description = "Jump to any windows (only works on Ura WM)."
prefix = "wd "
picker = "python ~/.config/fzfmenu/plugins/jumper.py picker"
runner = "python ~/.config/fzfmenu/plugins/jumper.py runner"

[[plugins]]
name = "history"
description = "Search and reuse past shell commands."
prefix = "hs "
picker = "python ~/.config/fzfmenu/plugins/history.py picker"
runner = "python ~/.config/fzfmenu/plugins/history.py runner"
reload = true

[[plugins]]
name = "sink"
description = "Switch default pipewire sink."
prefix = "sk "
picker = "python ~/.config/fzfmenu/plugins/sink.py picker"
runner = "python ~/.config/fzfmenu/plugins/sink.py runner"

[[plugins]]
name = "mpris"
description = "control play/pause with playerctl."
prefix = "mp "
picker = "python ~/.config/fzfmenu/plugins/mpris.py picker"
runner = "python ~/.config/fzfmenu/plugins/mpris.py runner"

[[plugins]]
name = "sing-box"
description = "manage sing-box user service."
prefix = "sb "
picker = "python ~/.config/fzfmenu/plugins/sing-box.py picker"
runner = "python ~/.config/fzfmenu/plugins/sing-box.py runner"
